version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  webserver:
    build:
      context: ./nginx-image
      dockerfile: Dockerfile
    container_name: nginx
    ports:
<<<<<<< HEAD
      - "8000:80"
=======
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
>>>>>>> 96fca41 (Update docker-compose.yml)
    depends_on:
      - app
    volumes:
      - ./:/var/www
    networks:
      - laravel

networks:
  laravel:
    driver: bridge