<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Sign Up</title>
    <!-- Font Awesome for eye/eye-slash icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Import Poppins font from Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>

    @section('title', 'Terms and Policy')

    @extends('layouts.app')


@section('termscontent')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
 <link rel="stylesheet" href="assets/css/termsandpolicy.css">
<style>
   
</style>

 <nav class="student-form-nav">
    <div class="student-form-nav-container">
      <img src="assets/images/student-form-logo.png" alt="Remitout Logo" class="student-form-logo">
      <div class="student-form-nav-links" id="student-form-nav-links">
        <a href="#home">Home</a>
        <a href="#resources">Resources</a>
        <a href="#deals">Special Deals</a>
        <a href="#services">Our Service</a>
        <a href="#schedule">Schedule Call</a>
        <a href="#support" class="student-form-nav-mobile">Support</a>
        <a href="#help" class="student-form-nav-mobile">Help</a>

        <div class="student-form-nav-buttons" display="style:none">
          <button class="student-form-login-btn" onclick="window.location.href='/login'">Log
            In</button>
          <button class="student-form-signup-btn" onclick="window.location.href='/signup'">Sign
            Up</button>
        </div>

      </div>

      <div class="student-form-menu-left">
        <a href="#" class="student-form-nav-mobile">Login</a>
        <div class="student-form-menu-icon-container" id="student-form-menu-icon-container">

          <div class="student-form-menu-icon" id="student-form-menu-icon">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
          </div>

        </div>
      </div>

    </div>
  </nav>

<div class="terms-container">
    <h1>Terms of Use</h1>
    <p>
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
    </p>
    <p>
        This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing of the rules & regulations, privacy policy and Terms of Use for access or usage of a website.
    </p>
    <p>
        Your use of www.remitout.com (the “Website”) for browsing our offerings and / or for transacting hereon constitutes a binding contract with Remitout Service Pvt. Ltd. (“Remitout”) and signifies your agreement to be bound by all of the terms and conditions appearing in this Terms of Use, including the Privacy Policy and other policies notices, as applicable, which are incorporated herein by reference, without any modifications to the same. If you disagree with any part of these Terms of Use or the other policies and notices incorporated herein by reference, please do not use the Website.
    </p>
    <p>
        Terms capitalized herein but not defined shall have the same meaning as given in the any of the other policies and notices contained in this Website.
    </p>
    <p>
        Nothing contained herein shall be construed to contradict or override anything contained in any of the other Policies or notices contained in this Website. In case there is a contradiction, the interpretation of Remitout shall be final and binding.
    </p>

    <h2>Membership, Registration & Eligibility</h2>
    <p>
        Use of the Website constitutes a binding contract between you and Remitout under the Indian Contracts Act 1872. Accordingly, persons who are "incompetent to contract" within the meaning of the said Act, e.g. minors, un-discharged insolvents, etc., are not permitted to use the Website or transact on it.
    </p>
    <p>
        While Remitout allows you to browse the Website without registering as a “User”, transacting hereon shall require you to register.
    </p>
    <p>
        Wherever registration is requested, you agree to provide Remitout with true, accurate and complete registration information. It shall further be your responsibility to inform Remitout of any changes to that information.
    </p>
    <p>
        Either an individual or an organization can register as Users on the Website. However, each User is required to specify, while registering themselves, their registration type clearly and accurately in the specifically designated space on the registration page. Remitout does not permit a) any other person to use the registered sections under your / your organization’s name, or b) access through a single name being made available to multiple users on a network, or c) access of an individual being used by an organization or vice versa. You shall be responsible for preventing such unauthorized use and for maintaining the confidentiality of your user identification details and password. You shall also be responsible for all activities that occur under your user identification details and password.
    </p>
    <p>
        You agree that if you provide any information that is untrue, inaccurate, not current or incomplete or Remitout has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, Remitout shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide you with access to the Website.
    </p>
    <p>
        If you are registered as an individual, this Website shall be available to you for your personal and non-commercial use only. If you are registered as an organization, your usage of this Website shall be for limited commercial purposes, inasmuch as the functionalities made available to you through the Website. You will not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from this Website.
    </p>
    <p>
        If you believe there has been any unauthorized use through your user identification details and password, you must notify us immediately by emailing us at <a href="mailto:support@remitout.com">support@remitout.com</a>.
    </p>

    <h2>Charges for Members</h2>
    <p>
        Membership on the Website is free. Remitout does not charge any fee for browsing and buying on the Website. However, Remitout reserves the right to charge associated costs, insurance costs, taxes, etc. as may be applicable. Remitout may also revise its fees from time to time. Remitout may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event, Remitout reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services. Revisions to the fees shall be posted on the Website and shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees.
    </p>

    <h2>Orders & Payments</h2>
    <p>
        All orders need to be completely compliant with all applicable laws and regulatory guidelines; any deviation from the same will be the sole responsibility of the User. (If you need any information on the applicable laws & guidelines please write to us at <a href="mailto:support@remitout.com">support@remitout.com</a>.)
    </p>
    <p>
        Minimum order values might be applicable to your transactions.
    </p>
    <p>
        All order values will be rounded off to the nearest currency unit.
    </p>
    <p>
        Rates are subject to major fluctuation.
    </p>
    <p>
        You may be required to pay a 'Merchant Service Fee' of 2% on the transaction value and is subject to change as decided by the respective payment gateway service provider.
    </p>
    <p>
        Applicable taxes, including but not limited to Goods & Services Tax (GST), shall be borne by you.
    </p>
    <p>
        All payments made by you shall be routed directly to our associates/channel partners who are RBI authorized foreign exchange dealers/service providers and who will deliver your forex/travel cards. Payments can be made by you physically at your bank branch, through credit/debit cards, or through internet banking, using the secured payment gateway of the associate/channel partner or by NEFT / RTGS. Invoices shall be issued by the relevant associate/channel partner.
    </p>
    <h3>Methods of payment available to you:</h3>
    <ul>
        <li>You can make the full payment as per the amount is shown on the Website using a payment gateway. (recommended)</li>
        <li>You can make a partial payment to block the exchange rates and transfer the balance amount as per invoice through NEFT/RTGS. Please note that this transfer has to be done on the same day in order to get the transaction processed. Failure to do so will result in forfeiture of the partial payment amount.</li>
        <li>You can complete the entire process on the Website and make the payment physically through your bank branch. In this case, however, the rates shown at the time or during the transaction will not be blocked and may differ as for the rates prevalent at the time of transferring the funds will be considered.</li>
    </ul>

    <h2>Cancellations & Refunds</h2>
    <p>
        For order canceled on client's request or non-compliance, the amount will be refunded after a deduction of Payment Gateway Charges and exchange charges. In case of orders placed through Partial payment, the refunds will be paid after deducting of all charges including but not limited to the payment gateway, exchange loss, bank charges, etc. The refunds should be settled within 30 days of submitting of request.
    </p>

    <h2>Platform for Limited Transactions</h2>
    <p>
        The Website is a platform through which Remitout brings together Users and various authorized forex dealers/service providers (the associates/channel partners of Remitout) to enable Users to send remittances abroad. However, Remitout is not and cannot be a party to or control in any manner any transaction between you and the associates/channel partners of Remitout, nor any other Users of the Website.
    </p>
    <p>
        All commercial / contractual terms, including without limitation price, rates, associated costs/fees, payment methods, payment terms, date, period and mode of delivery, warranties/guarantees related to products and services, etc., are provided on each individual product/channel partner’s page.
    </p>
    <p>
        Your placement of an order on the Website is an offer to accept such commercial / contractual terms to buy the product(s) in the order and it shall not be construed as acceptance of your offer to buy the product(s) ordered by Remitout or its associates/channel partners. Remitout and its associates/channel partners retain the right to cancel any such order placed by you, at its sole discretion and you shall be intimated of the same by way of an email / SMS. Any transaction price paid by you in case of such cancellation by Remitout, except as otherwise provided in this Terms of Use or elsewhere in the Website, shall be refunded to you.
    </p>
    <p>
        Pricing/rates of any product(s) as reflected on the Website may be erroneous due to some technical issue, typographical error or inadvertent publication of incorrect product information by Remitout. In such an event, Remitout may cancel such order(s) of yours.
    </p>
    <p>
        You release and indemnify Remitout and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the other Users of the Website and specifically waive any claims that you may have in this regard under any applicable law.
    </p>
    <p>
        Notwithstanding its reasonable efforts in this regard, Remitout cannot take responsibility nor control the information provided by other Users on the Website. You may find other Users’ information to be offensive, harmful, inconsistent, inaccurate or deceptive. Please use caution and practice safe trading when using the Website.
    </p>

    <h2>Statutory, Regulatory Compliances & Usage by Members</h2>
    <p>
        You shall be solely responsible for complying with all applicable laws including those in India for making payments through Remitout. You agree and confirm that you shall be aware of all regulatory norms applicable to you as a user of foreign exchange services.
    </p>
    <p>
        You undertake and confirm that:
    </p>
    <ul>
        <li>the source of funds for making the purchases/remittances through this Website belongs to you, the funds have been obtained by you legally and the foreign exchange shall not be used by you or your recipient for any illegal, immoral or prohibited purposes;</li>
        <li>the orders placed through the website shall not be designed for the purpose of any contravention or evasion of the provisions of the FEMA Act 1999 or of any Rule, Regulation, Notification, Direction or Order made thereunder;</li>
        <li>The foreign exchange purchased through this Website should be used within a maximum of sixty (60) days of its purchase. In case it is not possible to use the foreign exchange within the period of sixty (60) days, the same should be surrendered to the authorized dealer from whom it was purchased.</li>
    </ul>
    <p>
        You further agree and undertake to provide such information /documents as may reasonably satisfy us about the transaction in terms of the RBI Limits for Foreign Exchange Purchases or sales, and you shall be solely responsible and liable for any incorrect information provided by you.
    </p>
    <p>
        Remitout or any of the authorized dealers providing foreign exchange services through the Website shall not be responsible for any transaction executed through us by forged, false, inaccurate or unprofessed information. You will be solely responsible for such actions and liable to face all applicable regulatory actions.
    </p>
    <p>
        Compliance shall mean compliance with all applicable laws, including without limitation the Foreign Exchange Management Act, 1999, the Anti-Money Laundering Guidelines of the RBI (including rules made and notifications issued thereunder), the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, the Information Technology Act, 2000, the Prevention of Money Laundering Act, 2002 and the rules made thereunder, the Foreign Contribution Regulation Act, 1976 and the rules made thereunder & the Income Tax Act, 1961 and the rules made thereunder.
    </p>
    <p>
        Solely to enable Remitout to use the information you supply us with, so that we are not violating any rights you might have in your information, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in your information, in any media now known or not currently known, with respect to your information. We will only use your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.
    </p>
    <p>
        You understand that we have the right at all times to disclose any information (including the identity of the persons providing information on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, the disclosure of the information in connection with an investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
    </p>
    <p>
        Remitout reserves the right, but has no obligation, to monitor the materials posted on the Website by other Users. Remitout shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, you remain solely responsible for the information you provide or materials you post on the Website. Please be advised that the content posted on the Website does not necessarily reflect Remitout views. In no event shall Remitout assume or have any responsibility or liability for any content posted or for any claims, damages or losses resulting from the use of content and/or appearance of content on the Website, subject to what has been provided elsewhere in this Website. You hereby represent and warrant that you have all necessary rights in and to all content which you provide and all information it contains and that such content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.
    </p>

    <h2>Prohibited Activities</h2>
    <p>
        You hereby agree and acknowledge that commission of any of the following prohibited activities constitutes a material breach of the Terms of Use:
    </p>
    <ul>
        <li>Using the Website for any purpose in violation of any law in force in any jurisdiction across the world;</li>
        <li>Providing false or misleading information on the user-registration form or impersonating any person;</li>
        <li>Posting material that is in violation of the intellectual property rights of others or of the privacy or publicity rights of others;</li>
        <li>Uploading or transmitting any information, data, text, files, links, software, chat, communication or any other materials that are inflammatory, unlawful, harmful, threatening, abusive, invasive of another’s privacy, harassing, defamatory, slanderous, vulgar, obscene, hateful, racist, embarrassing or otherwise objectionable to any other person or entity, as determined by Remitout in its sole discretion;</li>
        <li>Uploading or transmitting any unsanctioned advertising, promotional materials, or any other forms of unsanctioned solicitation, including, but not being limited to, junk mail, spam, chain letters or any unsolicited mass distribution of e-mail;</li>
        <li>Uploading surveys, contests or pyramid schemes;</li>
        <li>Uploading improper questions or answers that are not related to the particular topic;</li>
        <li>Uploading information containing restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</li>
        <li>Uploading transmitting any information, data, text, files, links, software, chat, communication or any other material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</li>
        <li>Uploading or transmitting any information, data, text, files, links, software, chat, communication or any other material that provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</li>
        <li>Uploading or transmitting any information, data, text, files, links, software, chat, communication or any other material that harms or induces others to harm minors in any way;</li>
        <li>Uploading or transmitting any information, data, text, files, links, software, chat, communication or any other material that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation;</li>
        <li>Uploading or transmitting any information, data, text, files, links, software, chat, communication or any other material that, directly or indirectly, offers, attempts to offer, trades or attempts to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force;</li>
        <li>Stalking, harassing or otherwise harming others;</li>
        <li>Distributing software viruses, computer code, corrupted files or any other similar files, software or programs designed to interrupt, damage, destroy, or that may have the possibility to limit the functionality of, or cause harm in any manner to, the operation of another’s computer; or contains any trojan horses, worms, time bombs, cancelbots, Easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</li>
        <li>Collecting or storing personal data about other Users of the Website;</li>
        <li>Inducing, enticing, soliciting, recruiting, luring or attempting to induce, entice, solicit, recruit or lair users or members to another website which, according to Remitout, is a competitor of Remitout;</li>
        <li>Soliciting gambling or engaging in any gambling activity which Remitout, in its sole discretion, believes is or could be construed as being illegal;</li>
        <li>Doing or causing anything to be done to insert/upload any virus, corrupted files or any other similar software, malware, adware, spyware or any other programs that may have the ability to damage or harm or affect the operation of the Website or our servers in any manner;</li>
        <li>Using any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website, or in any way reproduce or circumvent the navigational structure or presentation of the Website, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website;</li>
        <li>Attempting to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password "mining" or any other illegitimate means;</li>
        <li>Probing, scanning or testing the vulnerability of the Website or any network connected to the Website or breaching the security or authentication measures on the Website or any network connected to the Website;</li>
        <li>Reverse looking-up, tracing or seeking to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by you, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Website;</li>
        <li>Making any negative, denigrating or defamatory statement(s) or comment(s) about Remitout, or the brand name or domain name used by Remitout, including the terms Remitout, the Website www.remitout.com, or otherwise engaging in any conduct or action that might tarnish the image or reputation of Remitout or otherwise tarnish or dilute any trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by Remitout;</li>
        <li>Engaging in any activity that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or Remitout's systems or networks, or any systems or networks connected to Remitout;</li>
        <li>Engaging in any other conduct that inhibits any other person from using or enjoying the services provided by us on the Website;</li>
        <li>Engaging in any other behavior deemed unacceptable by Remitout in its sole discretion, on the Website.</li>
    </ul>

    <h2>Investigation of Unlawful Activity</h2>
    <p>
        Remitout reserves the right to investigate complaints or reported violations of the Terms of Use and to take any action we deem fit and proper including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. Further, any unauthorized use of this Website may give rise to a claim for damages and/or be considered a criminal offense.
    </p>

    <h2>Remedies for Violations</h2>
    <p>
        Remitout reserves the right to seek all remedies available at law and in equity for violations of these Terms of Use, including but not limited to the right to block access for a particular user / from a particular IP address to our Website and its features.
    </p>

    <h2>Termination, Suspension, Limitation of Your Account</h2>
    <p>
        Remitout may, without prior notice, immediately terminate, limit your access to or suspend your account registered with us, any associated e-mail address and access to the Website. Cause for such termination, limitation of access or suspension shall include, but not be limited to, (a) breaches or violations of the Terms of Use or other incorporated guidelines, (b) requests by any competent law enforcement or other government agencies, (c) discontinuance or material modification to the Website (or any part thereof), (d) unexpected technical or security issues or problems, and/or (e) engagement by you in fraudulent or illegal activities. You further agree that all terminations, limitations of access and suspensions for cause shall be made in our sole discretion and that we shall not be liable to you or any third party for any termination of your account, any associated e-mail address or access to our Website. Termination of your account includes any or all of the following: (a) removal of access to all or part of the offerings within our Website, (b) deletion of your password and all related information, files, and content associated with or inside your account (or any part thereof) and (c) barring of further use of all or part of our Website.
    </p>

    <h2>Modifications to Terms of Use</h2>
    <p>
        Remitout reserves the right to change these Terms of Use at any time. Updated versions of the Terms of Use will appear on this Website and shall be effective immediately. Remitout may send a communication to you intimating you of any changes; however, it shall not be obligatory for Remitout to do so. You are responsible for regularly reviewing the Terms of Use, and non-communication of the revisions by Remitout shall not constitute a valid ground for non-acceptance of the revised Terms of Use. Continued use of the Website after any such changes appear on the Website shall constitute your consent to such changes.
    </p>

    <h2>Other Communications</h2>
    <p>
        When you use the Website or send emails or other data, information or communication to Remitout, you agree and understand that you are communicating with us through electronic records and you consent to receive communications via electronic records from us / our associates/channel partners periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise, as may appear on our records.
    </p>

    <h2>Advertisement and Sponsorship</h2>
    <p>
        This Website may contain advertising and sponsorship. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on the Website is accurate and complies with applicable laws. Remitout does not check the accuracy of such materials provided, and shall not be responsible for the illegality of or any error or inaccuracy in the advertisers' or sponsors’ materials. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Website, including payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Remitout shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Website.
    </p>

    <h2>Severability of Provisions</h2>
    <p>
        These Terms of Use incorporate by reference any notices contained on the Website, including but not limited to the Privacy Policy appearing on the Website, and together they constitute the entire agreement with respect to access to and use of the Website. If any provision of these Terms of Use is held to be unlawful, void or unenforceable by a competent court of law, then the impugned provision shall be deemed severable from the remaining provisions and shall not affect the enforceability and validity of the remaining provisions.
    </p>

    <h2>Indemnity</h2>
    <p>
        You agree and acknowledge that you shall defend, indemnify, protect and hold free Remitout, its subsidiaries, affiliates, associates / channel partners, teams, members, officers, directors, employees, agents, licensors, suppliers and other partners from and against all claims, actions or demands, loss, liabilities, and settlements, including, without limitation, reasonable legal and accounting fees, arising in connection with your usage of the Website or resulting from, or alleged to result from, such usage in violation of the Terms of Use or of any laws for the time being in force.
    </p>

    <h2>Disclaimer</h2>
    <p>
        The information, software, products and services included on this Website may include inaccuracies or typographical errors and Remitout will be entitled to rectify such inaccuracies or typographical errors. Remitout will not be liable/responsible for any decision that you may take based on such inaccurate information.
    </p>
    <p>
        Changes are periodically added to the information on the Website. Remitout is fully entitled to make improvements and/or changes in this Website at any time.
    </p>
    <p>
        Advice received via this Website should not be relied upon for personal, medical, legal or financial decisions and you should consult an appropriate professional for specific advice tailored to your situation. Remitout and/or its respective suppliers make no representations about the suitability, reliability, timeliness, and accuracy of the information, software, products, services, or any other items and related graphics contained on this Website for any purpose whatsoever. All such information, software, products, services, and related graphics are provided "as is" without warranty of any kind. Remitout and/or its respective suppliers hereby disclaim all warranties and conditions with regard to this information, software, products, services and related graphics, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title and non-infringement.
    </p>
    <p>
        In no event shall Remitout and/or its parents, subsidiaries, affiliates, officers, directors, employees, agents or suppliers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of this Website, with the delay or inability to use this Website, the provision of or failure to provide services, or for any information, software, products, services and related graphics obtained through this Website, or otherwise arising out of the use of this Website, whether based on contract, tort, strict liability or otherwise, even if Remitout or any of its suppliers has been advised of the possibility of damages, including liability associated with any viruses which may infect your computer equipment. If you are dissatisfied with any portion of this Website, or with any of these terms of use, your sole and exclusive remedy is to discontinue using this Website.
    </p>
    <p>
        Please ensure that all information given by you while booking is correct. For security reasons and to be able to advise you of any developments affecting your travel we need to be able to contact you by telephone and email and to have your correct address on record. If any or all of these contact details are not correctly given by you, we reserve the right to cancel the transaction at your risk and cost.
    </p>
    <p>
        The right to access and transact on the Website is reserved as is the right to use any particular credit card on the site for payment purposes.
    </p>

    <h2>Alternate Dispute Resolution</h2>
    <p>
        It is expressly agreed to and acknowledged by you that any dispute arising out of your use of the Website between you and Remitout shall be resolved through a three-step Alternate Dispute Resolution (“ADR”) mechanism.
    </p>
    <ul>
        <li><strong>Mutual Discussion</strong>: The parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both parties. In the event that the parties are unable to reach such an amicable solution within thirty (30) days of one party communicating the existence of a dispute to the other party, the dispute will be resolved by mediation, as detailed hereinbelow.</li>
        <li><strong>Mediation</strong>: In the event the parties are unable to amicably resolve the dispute by mutual discussion, said dispute will be referred to mediation to an impartial third person (the ‘Mediator’), to be appointed by Remitout. The said Mediator shall attempt to establish a dialogue between the parties, and mediate the dispute to the satisfaction of both parties. In the event the parties are unable to reach such a mutually acceptable solution even through mediation, then after thirty (30) days of the commencement of the mediation, the dispute shall be referred to arbitration, as detailed hereinbelow.</li>
        <li><strong>Arbitration</strong>: If the parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator, to be appointed by Remitout, and the award passed by such sole arbitrator will be valid and binding on both parties. The parties shall bear their own costs for the proceedings. The arbitration shall be conducted in English, and the seat of arbitration shall be the city of Mumbai in the state of Maharashtra, India.</li>
    </ul>
    <p>
        It is hereby agreed and acknowledged by both you and Remitout that no proceedings shall be instituted in any court of law by either party before the above three steps of ADR have been exhausted but no mutually acceptable solution has been reached.
    </p>

    <h2>Applicability of Law, Jurisdiction, and Limitation</h2>
    <p>
        Remitout and your use of the Website are governed by the laws prevailing in India. Your use of the Website indicates your consent to the exclusive jurisdiction of the appropriate courts in Mumbai, Maharashtra in all disputes arising out of or relating to this Agreement, in the event ADR fails. By your acceptance of the Terms of Use, you hereby waive all defenses of lack of jurisdiction, venue or forum non-convenience. Maintenance of the Website by Remitout is subject to existing laws and legal processes applicable to the same in India, and Remitout may comply with law enforcement or regulatory requests or requirements notwithstanding any term contrary to the Terms of Use, or any other terms, conditions or guidelines appearing in the Website and/or incorporated herein by reference. Any cause of action or claim that you may bring in connection with the Website must be commenced within the applicable time limits set by the existing laws in India after the claim or cause of action arises, otherwise such claim or cause of action shall be deemed to be barred by way of limitation. In any dispute between you and Remitout relating to this Website, you shall not be entitled to any attorneys’ fees, costs, and associated expenses.
    </p>

    <p class="mt-6">
        <a href="{{ route('signup') }}" class="text-blue-600 hover:underline">Back to Signup</a>
    </p>
</div>
@endsection
       
        
</body>
</html>